language: node_js
sudo: false
node_js:
  - 0.12

cache:
   directories:
     - node_modules
     - bower_components

before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - bower install

after_success:
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/**/lcov.info


deploy:
  provider: npm
  email: 
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: LunarDevelopment/afi
